id: 773aa78d-ba78-4dbb-8bf7-87e464627d4d
version: 12
vcShouldKeepItemLegacyProdMachine: false
name: SetDateField-Test.ym
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 846e61e5-24bd-4674-8a49-f3dbdea5926d
    type: start
    task:
      id: 846e61e5-24bd-4674-8a49-f3dbdea5926d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: a6a6c482-a6e0-4739-89a8-5b62ca3adf2a
    type: regular
    task:
      id: a6a6c482-a6e0-4739-89a8-5b62ca3adf2a
      version: -1
      name: Set Date Time of the Breach
      description: Sets a custom incident field with current date
      scriptName: SetDateField
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      fieldName:
        simple: datetimeofthebreach
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 3f6231d7-608a-45de-8242-d8ed7a036a13
    type: regular
    task:
      id: 3f6231d7-608a-45de-8242-d8ed7a036a13
      version: -1
      name: Close
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 265,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
