id: 'Account Enrichment - IAM'
version: -1
name: 'Account Enrichment - IAM'
description: |
  This playbook aims to retrieve user information from various vendors using the 'iam-get-user'.

  Current Supported Integrations:
  - Active Directory
  - AWS ILM
  - Clarizen IAM
  - Oracle IAM
  - ExceedLMS IAM
  - OKTA IAM
  - SAP-IAM
  - Atlassian IAM
  - Envoy IAM
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6dc28368-259a-4c24-88ee-bf2fc7a6dc65
    type: start
    task:
      id: 6dc28368-259a-4c24-88ee-bf2fc7a6dc65
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -3820,
          "y": -280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: de8a167f-955c-4b44-85d9-7091088ba913
    type: title
    task:
      id: de8a167f-955c-4b44-85d9-7091088ba913
      version: -1
      name: OKTA IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6150,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: a1413e4e-1481-416a-8d10-2e98b3796666
    type: title
    task:
      id: a1413e4e-1481-416a-8d10-2e98b3796666
      version: -1
      name: AWS-ILM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4520,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a087c01b-759e-4c07-8020-3f9442a2eed8
    type: title
    task:
      id: a087c01b-759e-4c07-8020-3f9442a2eed8
      version: -1
      name: 'Clarizen IAM '
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4920,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 15d2301b-89d8-461d-8db5-88b640ce9206
    type: title
    task:
      id: 15d2301b-89d8-461d-8db5-88b640ce9206
      version: -1
      name: Envoy IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -7390,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 441ab831-8212-41cb-8af1-8c5920b9ba5c
    type: title
    task:
      id: 441ab831-8212-41cb-8af1-8c5920b9ba5c
      version: -1
      name: ExceedLMS IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -5740,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 9129c3e7-3f84-42df-8002-286c4b55ffed
    type: condition
    task:
      id: 9129c3e7-3f84-42df-8002-286c4b55ffed
      version: -1
      name: Is OKTA IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: Okta IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6150,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a561f83f-4702-4942-87b9-bacb5cdefe72
    type: condition
    task:
      id: a561f83f-4702-4942-87b9-bacb5cdefe72
      version: -1
      name: Is AWS-ILM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: AWS-ILM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4520,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d4b000a2-44c3-4652-822e-825d4f638397
    type: condition
    task:
      id: d4b000a2-44c3-4652-822e-825d4f638397
      version: -1
      name: Is Clarizen IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: Clarizen IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4920,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: a88a3693-614d-4434-8c21-7805d9600662
    type: condition
    task:
      id: a88a3693-614d-4434-8c21-7805d9600662
      version: -1
      name: Is Envoy IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "18"
    scriptarguments:
      brandname:
        simple: Envoy IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -7390,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 230f1f78-5ea3-4b2c-839a-a57d5b68f89d
    type: condition
    task:
      id: 230f1f78-5ea3-4b2c-839a-a57d5b68f89d
      version: -1
      name: Is ExceedLMS IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: ExceedLMS IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -5740,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 31e2518d-7497-4a2f-8736-66f7bbf603a0
    type: regular
    task:
      id: 31e2518d-7497-4a2f-8736-66f7bbf603a0
      version: -1
      name: IAM Get User
      description: Retrieves a single user resource.
      script: '|||iam-get-user'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      user-profile:
        simple: '{"username":"${inputs.Username}"}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -5120,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: decfa768-adb5-45d9-8f61-ae0877af2f54
    type: title
    task:
      id: decfa768-adb5-45d9-8f61-ae0877af2f54
      version: -1
      name: Atlassian IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6980,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 86101ac1-3c26-4239-84f9-f864286faba1
    type: condition
    task:
      id: 86101ac1-3c26-4239-84f9-f864286faba1
      version: -1
      name: Is Atlassian IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "18"
    scriptarguments:
      brandname:
        simple: Atlassian IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6980,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 609f672c-f241-465a-82bd-1ceb632b8802
    type: title
    task:
      id: 609f672c-f241-465a-82bd-1ceb632b8802
      version: -1
      name: OracleIAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -5330,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 53e4e8f6-3218-4953-85e6-d8db410bcc22
    type: condition
    task:
      id: 53e4e8f6-3218-4953-85e6-d8db410bcc22
      version: -1
      name: Is Oracle IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: Oracle IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -5330,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: c1eb2001-1a37-4e3a-8d27-0bfd57d2f217
    type: condition
    task:
      id: c1eb2001-1a37-4e3a-8d27-0bfd57d2f217
      version: -1
      name: Check if the input is specidied.
      description: Check if a username was provided.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "2"
      - "3"
      - "4"
      - "5"
      - "1"
      - "12"
      - "14"
      - "19"
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.Username
            iscontext: true
    view: |-
      {
        "position": {
          "x": -3820,
          "y": -150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: a86e5774-dbda-49f8-8a5c-c34a89bbc0b9
    type: title
    task:
      id: a86e5774-dbda-49f8-8a5c-c34a89bbc0b9
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -3820,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: e959d54e-4d52-4ea7-8425-d5c94572357e
    type: regular
    task:
      id: e959d54e-4d52-4ea7-8425-d5c94572357e
      version: -1
      name: IAM Get User
      description: Retrieves a single user resource.
      script: '|||iam-get-user'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      user-profile:
        simple: '{"userName":"${inputs.Username}"}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -7180,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: ac940a98-001c-4932-8b61-6269635ed480
    type: title
    task:
      id: ac940a98-001c-4932-8b61-6269635ed480
      version: -1
      name: SAP-IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6560,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: b3076d71-2659-4839-828c-3a165d2bcf55
    type: condition
    task:
      id: b3076d71-2659-4839-828c-3a165d2bcf55
      version: -1
      name: Is SAP-IAM Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: SAP-IAM
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -6560,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 5baff5d9-899f-448e-83bf-a810655e3401
    type: title
    task:
      id: 5baff5d9-899f-448e-83bf-a810655e3401
      version: -1
      name: Active Directory - IAM
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4100,
          "y": 35
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: b52b533e-a1b0-4de8-8567-432471104e5b
    type: condition
    task:
      id: b52b533e-a1b0-4de8-8567-432471104e5b
      version: -1
      name: Is Active Directory Integration Enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "11"
    scriptarguments:
      brandname:
        simple: Active Directory Query v2
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -4100,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 875,
        "width": 3950,
        "x": -7390,
        "y": -280
      }
    }
  }
inputs:
- key: Username
  value: {}
  required: false
  description: Specify the useranme
  playbookInputQuery:
outputs:
- contextPath: IAM.Vendor.action
  description: The command name.
- contextPath: IAM.Vendor.username
  description: The employee username in the app.
- contextPath: IAM.Vendor.success
  description: If true, the command was executed successfully.
- contextPath: IAM.Vendor.instanceName
  description: The integration instance name.
- contextPath: IAM.Vendor.id
  description: The employee user ID in the app.
- contextPath: IAM.Vendor.errorMessage
  description: The reason the API failed.
- contextPath: IAM.Vendor.errorCode
  description: The HTTP error response code.
- contextPath: IAM.Vendor.email
  description: The employee email address.
- contextPath: IAM.Vendor.details
  description: Tells the user if the API was successful, otherwise provides error information.
- contextPath: IAM.Vendor.brand
  description: The integration name.
- contextPath: IAM.Vendor.active
  description: If true the employee status is active.
- contextPath: IAM.Vendor
  description: Queried IAM vendor name.
  type: unknown
- contextPath: IAM.UserProfile
  description: The user profile.
- contextPath: IAM
  description: Returened IAM infomration from the query.
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 6.5.0
